packages:
  - packages/mcp
  - packages/app
allowBuilds:
  '@swc/core': true
  '@tailwindcss/oxide': true
  esbuild: true
preferWorkspacePackages: true
shamefullyHoist: true
sharedWorkspaceLockfile: true
strictPeerDependencies: false
