import { readFileSync } from "node:fs";

export interface PdfFixturePage {
  lines?: string[];
  empty?: boolean;
}

function serializePdf(objects: string[], trailer = ""): Uint8Array {
  let text = "%PDF-1.4\n";
  const offsets = [0];
  for (const [index, body] of objects.entries()) {
    offsets.push(Buffer.byteLength(text, "latin1"));
    text += `${index + 1} 0 obj\n${body}\nendobj\n`;
  }
  const xref = Buffer.byteLength(text, "latin1");
  text += `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n`;
  text += offsets.slice(1).map((offset) => `${String(offset).padStart(10, "0")} 00000 n \n`).join("");
  text += `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R ${trailer} >>\nstartxref\n${xref}\n%%EOF\n`;
  return new Uint8Array(Buffer.from(text, "latin1"));
}

function pdfString(value: string): string {
  if (/[^\x20-\x7e]/u.test(value)) throw new Error("Fixture text must be printable ASCII.");
  return value.replaceAll("\\", "\\\\").replaceAll("(", "\\(").replaceAll(")", "\\)");
}

export function buildPdfFixture(pages: PdfFixturePage[]): Uint8Array {
  if (pages.length === 0) throw new Error("At least one fixture page is required.");
  const objects = [
    "<< /Type /Catalog /Pages 2 0 R >>",
    `<< /Type /Pages /Kids [${pages.map((_, i) => `${4 + i * 2} 0 R`).join(" ")}] /Count ${pages.length} >>`,
    "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>",
  ];
  for (const [index, page] of pages.entries()) {
    const stream = page.empty ? "" : `BT /F1 12 Tf 16 TL 72 720 Td ${(page.lines ?? [])
      .map((line, i) => `${i ? "T* " : ""}(${pdfString(line)}) Tj`).join(" ")} ET`;
    objects.push(`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 3 0 R >> >> /Contents ${5 + index * 2} 0 R >>`);
    objects.push(`<< /Length ${Buffer.byteLength(stream)} >>\nstream\n${stream}\nendstream`);
  }
  return serializePdf(objects);
}

// Deterministic blank PDF 1.4 revision-2 fixture, generated by the original
// test helper. Its test-only user password is "secret"; no runtime crypto is needed.
const PASSWORD_PROTECTED_FIXTURE_PATH = new URL("./password-protected.pdf", import.meta.url);

export function buildEncryptedPdfFixture(): Uint8Array {
  return new Uint8Array(readFileSync(PASSWORD_PROTECTED_FIXTURE_PATH));
}

export function buildMalformedPdfFixture(): Uint8Array {
  return new TextEncoder().encode("not-a-pdf");
}
