export const TOOL_NAME = {
  CODEBASE_CONTEXT: "codebase_context",
  CODEBASE_EDIT_CONTEXT: "codebase_edit_context",
  CODEBASE_SEARCH: "codebase_search",
  CODEBASE_PEEK: "codebase_peek",
  FIND_SIMILAR: "find_similar",
  IMPLEMENTATION_LOOKUP: "implementation_lookup",
  INDEX_CODEBASE: "index_codebase",
  INDEX_STATUS: "index_status",
  INDEX_HEALTH_CHECK: "index_health_check",
  INDEX_METRICS: "index_metrics",
  INDEX_LOGS: "index_logs",
  CALL_GRAPH: "call_graph",
  CALL_GRAPH_PATH: "call_graph_path",
  PR_IMPACT: "pr_impact",
  CODE_COMMUNITIES: "code_communities",
  ARCHITECTURE_CONTEXT: "architecture_context",
  ADD_KNOWLEDGE_BASE: "add_knowledge_base",
  LIST_KNOWLEDGE_BASES: "list_knowledge_bases",
  REMOVE_KNOWLEDGE_BASE: "remove_knowledge_base",
  PI_KNOWLEDGE_BASE_ADD: "knowledge_base_add",
  PI_KNOWLEDGE_BASE_LIST: "knowledge_base_list",
  PI_KNOWLEDGE_BASE_REMOVE: "knowledge_base_remove",
  INDEX_VISUALIZE: "index_visualize",
} as const;

export type ToolName = (typeof TOOL_NAME)[keyof typeof TOOL_NAME];

export const PORTABLE_TOOL_NAMES = [
  TOOL_NAME.CODEBASE_CONTEXT,
  TOOL_NAME.CODEBASE_EDIT_CONTEXT,
  TOOL_NAME.CODEBASE_SEARCH,
  TOOL_NAME.CODEBASE_PEEK,
  TOOL_NAME.INDEX_CODEBASE,
  TOOL_NAME.INDEX_STATUS,
  TOOL_NAME.INDEX_HEALTH_CHECK,
  TOOL_NAME.INDEX_METRICS,
  TOOL_NAME.INDEX_LOGS,
  TOOL_NAME.FIND_SIMILAR,
  TOOL_NAME.IMPLEMENTATION_LOOKUP,
  TOOL_NAME.CALL_GRAPH,
  TOOL_NAME.CALL_GRAPH_PATH,
  TOOL_NAME.PR_IMPACT,
  TOOL_NAME.ARCHITECTURE_CONTEXT,
  TOOL_NAME.CODE_COMMUNITIES,
] as const;

export const OPENCODE_TOOL_NAMES = [
  TOOL_NAME.CODEBASE_CONTEXT,
  TOOL_NAME.CODEBASE_EDIT_CONTEXT,
  TOOL_NAME.CODEBASE_SEARCH,
  TOOL_NAME.CODEBASE_PEEK,
  TOOL_NAME.INDEX_CODEBASE,
  TOOL_NAME.INDEX_STATUS,
  TOOL_NAME.INDEX_HEALTH_CHECK,
  TOOL_NAME.INDEX_METRICS,
  TOOL_NAME.INDEX_LOGS,
  TOOL_NAME.FIND_SIMILAR,
  TOOL_NAME.CALL_GRAPH,
  TOOL_NAME.CALL_GRAPH_PATH,
  TOOL_NAME.IMPLEMENTATION_LOOKUP,
  TOOL_NAME.ADD_KNOWLEDGE_BASE,
  TOOL_NAME.LIST_KNOWLEDGE_BASES,
  TOOL_NAME.REMOVE_KNOWLEDGE_BASE,
  TOOL_NAME.PR_IMPACT,
  TOOL_NAME.ARCHITECTURE_CONTEXT,
  TOOL_NAME.CODE_COMMUNITIES,
  TOOL_NAME.INDEX_VISUALIZE,
] as const;

export const PI_TOOL_NAMES = [
  TOOL_NAME.CODEBASE_CONTEXT,
  TOOL_NAME.CODEBASE_EDIT_CONTEXT,
  TOOL_NAME.CODEBASE_SEARCH,
  TOOL_NAME.CODEBASE_PEEK,
  TOOL_NAME.FIND_SIMILAR,
  TOOL_NAME.IMPLEMENTATION_LOOKUP,
  TOOL_NAME.INDEX_CODEBASE,
  TOOL_NAME.INDEX_STATUS,
  TOOL_NAME.INDEX_HEALTH_CHECK,
  TOOL_NAME.INDEX_METRICS,
  TOOL_NAME.INDEX_LOGS,
  TOOL_NAME.CALL_GRAPH,
  TOOL_NAME.CALL_GRAPH_PATH,
  TOOL_NAME.PR_IMPACT,
  TOOL_NAME.ARCHITECTURE_CONTEXT,
  TOOL_NAME.CODE_COMMUNITIES,
  TOOL_NAME.PI_KNOWLEDGE_BASE_LIST,
  TOOL_NAME.PI_KNOWLEDGE_BASE_ADD,
  TOOL_NAME.PI_KNOWLEDGE_BASE_REMOVE,
] as const;

// MCP clients expose the portable retrieval core plus the knowledge-base management tools.
// Knowledge-base tools are intentionally NOT part of PORTABLE_TOOL_NAMES: that set is a Pi
// contract (tests/pi-package.test.ts asserts Pi exposes every portable name), and Pi exposes
// the knowledge-base tools under its own host-specific aliases (PI_KNOWLEDGE_BASE_*).
export const MCP_TOOL_NAMES = [
  ...PORTABLE_TOOL_NAMES,
  TOOL_NAME.ADD_KNOWLEDGE_BASE,
  TOOL_NAME.LIST_KNOWLEDGE_BASES,
  TOOL_NAME.REMOVE_KNOWLEDGE_BASE,
] as const;
