"""
agentmemory V3 — Storage backend protocol.

Pluggable storage abstraction. Ships SQLite (default) and Postgres.
Implement StorageBackend to add Redis, Qdrant, Weaviate, etc.
"""

from __future__ import annotations

from typing import Optional, Protocol, runtime_checkable

from ..models import AuditEvent, Edge, MemoryNode, Namespace


@runtime_checkable
class StorageBackend(Protocol):
    """Protocol for storage backends. Implement to add new backends."""

    # ---- Writes ----
    async def save_node(self, node: MemoryNode) -> None: ...
    async def save_nodes_batch(self, nodes: list[MemoryNode]) -> None: ...
    async def delete_node(self, nid: str) -> None: ...
    async def save_edge(self, edge: Edge) -> None: ...
    async def delete_edges_for_node(self, nid: str) -> int: ...
    async def log_audit(self, event: AuditEvent) -> None: ...

    # ---- Reads ----
    async def load_node(self, nid: str) -> Optional[MemoryNode]: ...
    async def get_all_nodes(self) -> list[MemoryNode]: ...
    async def get_active_nodes(self, min_imp: float = 0.0) -> list[MemoryNode]: ...
    async def count(self, kind: Optional[str] = None) -> int: ...
    async def fulltext_search(self, query: str, limit: int = 50) -> list[tuple[str, float]]: ...
    async def query_by_kind(self, kinds: list[str], limit: int = 100) -> list[MemoryNode]: ...
    async def query_by_tags(self, tags: set[str], limit: int = 100) -> list[MemoryNode]: ...
    async def query_by_session(self, sid: str) -> list[MemoryNode]: ...
    async def query_by_source(self, src: str, limit: int = 100) -> list[MemoryNode]: ...
    async def query_by_namespace(self, ns: Namespace, limit: int = 100) -> list[MemoryNode]: ...
    async def query_by_time_range(self, start: Optional[float] = None,
                                   end: Optional[float] = None,
                                   limit: int = 100) -> list[MemoryNode]: ...
    async def load_edges(self) -> list[Edge]: ...
    async def get_audit_log(self, node_id: Optional[str] = None,
                             limit: int = 100) -> list[AuditEvent]: ...

    # ---- GDPR ----
    async def delete_by_source(self, source: str) -> int: ...
    async def delete_by_namespace(self, ns: Namespace) -> int: ...
    async def redact_audit_log(self, node_ids: list[str]) -> int: ...
    async def get_node_ids_by_source(self, source: str) -> list[str]: ...
    async def get_node_ids_by_namespace(self, ns: Namespace) -> list[str]: ...

    # ---- Lifecycle ----
    async def close(self) -> None: ...
