from playwright.sync_api import sync_playwright
import os
abs_path = '/workspace/osquestador-auditor/prototipo_v12/index.html'
out = '/workspace/osquestador-auditor/prototipo_v12/screenshots'
os.makedirs(out, exist_ok=True)
shots = []
def shot(page, name):
    p = f'{out}/{name}.png'
    page.screenshot(path=p)
    shots.append(name)
    print(f'OK {name}', flush=True)
with sync_playwright() as p:
    b = p.chromium.launch()
    ctx = b.new_context(viewport={'width': 1280, 'height': 800})
    page = ctx.new_page()
    page.goto('file://' + abs_path)
    page.wait_for_load_state('domcontentloaded')
    page.wait_for_timeout(300)
    shot(page, 'V12_desktop_light')
    page.evaluate('toggleTheme()')
    page.wait_for_timeout(200)
    shot(page, 'V12_desktop_dark')
    page.evaluate('toggleTheme()')
    page.evaluate('showView("api")')
    page.wait_for_timeout(100)
    shot(page, 'V12_api')
    page.evaluate('showView("dashboard")')
    page.locator('.sidebar__new').click()
    page.wait_for_timeout(300)
    shot(page, 'V12_bandeja')
    page.locator('#scrim-bandeja').click()
    page.wait_for_timeout(200)
    page.evaluate('showView("chat")')
    page.fill('#chat-input', 'este es un mensaje de prueba para el contador de tokens')
    page.wait_for_timeout(200)
    shot(page, 'V12_chat_tokens')
    ctx.close()
    ctx2 = b.new_context(viewport={'width': 390, 'height': 844})
    page2 = ctx2.new_page()
    page2.goto('file://' + abs_path)
    page2.wait_for_load_state('domcontentloaded')
    page2.wait_for_timeout(300)
    shot(page2, 'V12_mobile_dashboard')
    page2.locator('.header__menu').click()
    page2.wait_for_timeout(400)
    shot(page2, 'V12_mobile_drawer')
    ctx2.close()
    b.close()
print('DONE', len(shots), 'screenshots')
