use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChunkMetadata {
    pub file_path: String,
    pub start_line: u32,
    pub end_line: u32,
    pub chunk_type: String,
    pub name: Option<String>,
    pub language: String,
    pub file_hash: String,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Language {
    TypeScript,
    TypeScriptTsx,
    JavaScript,
    JavaScriptJsx,
    Python,
    Rust,
    Swift,
    Go,
    Java,
    CSharp,
    Ruby,
    C,
    Cpp,
    Metal,
    Json,
    Toml,
    Yaml,
    Bash,
    Markdown,
    Html,
    Php,
    Apex,
    Zig,
    Gdscript,
    Matlab,
    Xml,
    Svg,
    Text,
}

impl Language {
    pub fn from_extension(ext: &str) -> Self {
        match ext.to_lowercase().as_str() {
            "ts" | "mts" | "cts" => Language::TypeScript,
            "tsx" => Language::TypeScriptTsx,
            "js" | "mjs" | "cjs" => Language::JavaScript,
            "jsx" => Language::JavaScriptJsx,
            "py" | "pyi" => Language::Python,
            "rs" => Language::Rust,
            "swift" => Language::Swift,
            "go" => Language::Go,
            "java" => Language::Java,
            "cs" => Language::CSharp,
            "rb" => Language::Ruby,
            "c" | "h" => Language::C,
            "cpp" | "cc" | "cxx" | "hpp" | "hxx" => Language::Cpp,
            "metal" => Language::Metal,
            "json" => Language::Json,
            "toml" => Language::Toml,
            "yaml" | "yml" => Language::Yaml,
            "sh" | "bash" | "zsh" => Language::Bash,
            "md" | "mdx" => Language::Markdown,
            "html" | "htm" => Language::Html,
            "txt" => Language::Text,
            "php" | "inc" => Language::Php,
            "zig" => Language::Zig,
            "gd" => Language::Gdscript,
            "m" => Language::Matlab,
            "xml" => Language::Xml,
            "svg" => Language::Svg,
            "cls" | "trigger" => Language::Apex,
            _ => Language::Text,
        }
    }

    pub fn as_str(&self) -> &'static str {
        match self {
            Language::TypeScript => "typescript",
            Language::TypeScriptTsx => "tsx",
            Language::JavaScript => "javascript",
            Language::JavaScriptJsx => "jsx",
            Language::Python => "python",
            Language::Rust => "rust",
            Language::Swift => "swift",
            Language::Go => "go",
            Language::Java => "java",
            Language::CSharp => "csharp",
            Language::Ruby => "ruby",
            Language::C => "c",
            Language::Cpp => "cpp",
            Language::Metal => "metal",
            Language::Json => "json",
            Language::Toml => "toml",
            Language::Yaml => "yaml",
            Language::Bash => "bash",
            Language::Markdown => "markdown",
            Language::Html => "html",
            Language::Php => "php",
            Language::Zig => "zig",
            Language::Gdscript => "gdscript",
            Language::Matlab => "matlab",
            Language::Xml => "xml",
            Language::Svg => "svg",
            Language::Apex => "apex",
            Language::Text => "text",
        }
    }

    pub fn from_string(s: &str) -> Self {
        match s.to_lowercase().as_str() {
            "typescript" | "ts" => Language::TypeScript,
            "tsx" => Language::TypeScriptTsx,
            "javascript" | "js" => Language::JavaScript,
            "jsx" => Language::JavaScriptJsx,
            "python" | "py" => Language::Python,
            "rust" | "rs" => Language::Rust,
            "swift" => Language::Swift,
            "go" => Language::Go,
            "java" => Language::Java,
            "csharp" | "cs" | "c#" => Language::CSharp,
            "ruby" | "rb" => Language::Ruby,
            "c" => Language::C,
            "cpp" | "c++" => Language::Cpp,
            "metal" => Language::Metal,
            "json" => Language::Json,
            "toml" => Language::Toml,
            "yaml" | "yml" => Language::Yaml,
            "bash" | "sh" | "zsh" => Language::Bash,
            "markdown" | "md" => Language::Markdown,
            "html" | "htm" => Language::Html,
            "text" | "txt" => Language::Text,
            "php" => Language::Php,
            "zig" => Language::Zig,
            "gdscript" | "gd" => Language::Gdscript,
            "matlab" | "m" => Language::Matlab,
            "xml" => Language::Xml,
            "svg" => Language::Svg,
            "apex" => Language::Apex,
            _ => Language::Text,
        }
    }
}
