/*
 * Copyright (c) "Neo4j"
 * Neo4j Sweden AB [https://neo4j.com]
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.neo4j.cypher.internal.util.helpers

import org.neo4j.cypher.internal.util.CrossCompilation

/**
 * A workaround for the fact that code generated by the Scala 3 compiler for lazy vals is not understood by TeaVM.
 * See https://github.com/konsoletyper/teavm/discussions/887 for more details.
 */
sealed trait LazyVal[A] {
  def value: A
}

object LazyVal {

  def apply[A](initializer: => A): LazyVal[A] = {
    if (CrossCompilation.isTeaVM()) {
      new LazyValJavascript(() => initializer)
    } else {
      new LazyValScala(() => initializer)
    }
  }

  private class LazyValScala[A](private var initializer: () => A) extends LazyVal[A] {

    override lazy val value: A = {
      val result = initializer()
      initializer = null
      result
    }
  }

  private class LazyValJavascript[A](private var initializer: () => A) extends LazyVal[A] {
    private var initialized: Boolean = false
    private var computedValue: A = _

    override def value: A = {
      if (!initialized) {
        computedValue = initializer()
        initializer = null
        initialized = true
      }
      computedValue
    }
  }

}
