/*
 * Copyright (c) "Neo4j"
 * Neo4j Sweden AB [https://neo4j.com]
 *
 * This file is part of Neo4j.
 *
 * Neo4j is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */
package org.neo4j.cypher.cucumber.synthesise.generator

import io.cucumber.datatable.DataTable
import org.neo4j.cypher.cucumber.steps.CypherCucumberSteps.ExpectedGqlNotification
import org.neo4j.cypher.cucumber.synthesise.CucumberSalad
import org.neo4j.cypher.cucumber.synthesise.generator.Filter.doNotContainAst
import org.neo4j.cypher.cucumber.synthesise.glue.scenario.AssertGqlWarning
import org.neo4j.cypher.cucumber.synthesise.glue.scenario.ExpectError
import org.neo4j.cypher.cucumber.synthesise.glue.scenario.HavingExecuted
import org.neo4j.cypher.cucumber.synthesise.glue.scenario.RecordedScenario
import org.neo4j.cypher.cucumber.synthesise.glue.scenario.RecordedStep
import org.neo4j.cypher.cucumber.synthesise.glue.scenario.SetupExecution
import org.neo4j.cypher.cucumber.synthesise.glue.scenario.TestExecution
import org.neo4j.cypher.internal.ast.SchemaCommand
import org.neo4j.cypher.internal.expressions.MapExpression
import org.neo4j.cypher.internal.expressions.NodePattern
import org.neo4j.cypher.internal.expressions.Property
import org.neo4j.cypher.internal.label_expressions.LabelExpressionLeafName
import org.neo4j.cypher.internal.util.Foldable.SkipChildren

import java.nio.file.Paths
import java.util.concurrent.atomic.AtomicLong

import scala.collection.View
import scala.jdk.CollectionConverters.SeqHasAsJava

class AddIndex(val args: CucumberSalad.Ingredients) extends ScenarioGenerator with ScenarioRenderer {
  override val name: String = "add-index"

  private val counter = new AtomicLong(0)

  override def filter: Filter = super.filter
    .steps[SetupExecution](_.nonEmpty)
    .steps[ExpectError](_.isEmpty)
    .setupQueries(_.forall(doNotContainAst[SchemaCommand]))
    .scenario(scenario => labelsAndProps(scenario).values.exists(_.nonEmpty))

  def generateScenarios(filteredScenarios: View[RecordedScenario]): IterableOnce[GeneratedScenario] = {
    filteredScenarios
      .map(scenario => scenario -> labelsAndProps(scenario))
      .collect {
        case (scenario, propsByLabel) if propsByLabel.values.exists(_.nonEmpty) =>
          generateScenario(scenario, propsByLabel)
      }
  }

  private def generateScenario(
    scenario: RecordedScenario,
    propsByLabel: Map[String, Set[String]]
  ): GeneratedScenario = {
    val exampleRows = for {
      (label, props) <- propsByLabel.toSeq
      keyCombination <- props.subsets(1) ++ props.subsets(2)
    } yield Seq(label, keyCombination.map(p => s"n.$p").mkString(", "))
    val examples = Option(DataTable.create(exampleRows.prepended(Seq("label", "props")).map(_.asJava).asJava))
      .filter(_.height() > 2)

    val (label, props) = if (examples.isDefined) ("<label>", "<props>") else (exampleRows.head(0), exampleRows.head(1))
    val steps = relaxNotificationAssertionsForSynthesizedIndexScenario(scenario.steps).prependedAll(Seq(
      HavingExecuted(s"CREATE INDEX FOR (n:$label) ON ($props) // Generated query"),
      HavingExecuted("CALL db.awaitIndexes() // Generated query")
    ))
    val name = s"Generated ${counter.incrementAndGet()}: ${scenario.name}"
    val featurePath = Paths.get(scenario.uri.getSchemeSpecificPart)
    val comment = "Generated by adding indexes, based on " + scenario.source
    GeneratedScenario(name, steps, featurePath, comment, scenario.tags, examples)
  }

  private def labelsAndProps(scenario: RecordedScenario): Map[String, Set[String]] = scenario.steps.view
    .collect { case e: TestExecution => args.parser.parse(e.cypher) }
    .flatMap(labelsAndProps)
    .groupMap { case (label, _) => label } { case (_, propKey) => propKey }
    .view.mapValues(_.toSet)
    .toMap

  private def labelsAndProps(query: ParsedQuery): Set[(String, String)] = {
    query.ast.folder.treeFold(Set.empty[(String, String)]) {
      case NodePattern(varOpt, Some(labelExp), propsOpt, whereOpt) => acc =>
          val propKeys = propsOpt match {
            case Some(MapExpression(items)) => items.map(_._1.name)
            case _                          => Seq.empty[String]
          }
          val propKeysFromWhere = (varOpt, whereOpt) match {
            case (Some(variable), Some(where)) => where.folder.treeFold(Seq.empty[String]) {
                case Property(map, key) if map == variable => acc => SkipChildren(acc.appended(key.name))
              }
            case _ => Seq.empty[String]
          }
          val result = for {
            labelName <- labelExp.folder.findAllByClass[LabelExpressionLeafName].map(_.name)
            propKey <- (propKeys ++ propKeysFromWhere)
          } yield labelName -> propKey
          SkipChildren(acc.concat(result))
    }
  }

  /**
   * CREATE INDEX (+ await) can change planner slots and thus 03N96 (and similar) notification text while codes stay
   * meaningful. AddIndex only checks index behaviour, so keep code expectations and accept any description
   * (`${regex:.*}` matches [[org.neo4j.cypher.cucumber.glue.regular.steps.RegularErrorSteps.buildRegexFromTemplate]]).
   */
  private def relaxNotificationAssertionsForSynthesizedIndexScenario(steps: Seq[RecordedStep]): Seq[RecordedStep] =
    steps.map {
      case AssertGqlWarning(exp) => AssertGqlWarning(relaxNotificationExpectation(exp))
      case step                  => step
    }

  private def relaxNotificationExpectation(exp: ExpectedGqlNotification): ExpectedGqlNotification = {
    val rows = exp.warnings.map { w =>
      val codeCell = if (w.optional) s"${w.code}?" else w.code
      java.util.List.of[String](codeCell, "${regex:.*}")
    }
    ExpectedGqlNotification(
      DataTable.create((java.util.List.of("code", "description") +: rows).asJava)
    )
  }
}
